language: python
sudo: false

cache:
  - pip
  - apt

addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - libc6
      - g++
      - gfortran
      - libhdf5-serial-dev

python:
  - 2.7

install: pip install h5py

script: py.test .
